name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [ 3.8 ]
        os:  [ ubuntu-20.04 ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Edit PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install pip dependencies
        run: |
            python -m pip install --user --upgrade setuptools wheel
            python -m pip install --user -r requirements.txt

      - name: Run Python tests
        run: |
            python -m pytest tests
